### ISSUE TITLE
Erro on start on HA 93.1

### ISSUE THREAD

**Issue by ik0adr** [pkozul/ha-tts-bluetooth-speaker#13]
On 93.1 I get the following error:

[homeassistant.helpers.config_validation] Your configuration contains extra keys that the platform does not support.
Please remove [address].  (See /home/homeassistant/.homeassistant/configuration.yaml, line 325). 
Offending data: {"platform": "tts_bluetooth_speaker", "address": "07:52:41:A5:72:73"}

Thanks..

**Comment by ik0adr** [comment]
It is a HA problem also for other devices.
Thanks anyway..

**Comment by ik0adr** [comment]
[https://github.com/home-assistant/home-assistant/issues/24006](url)

**Comment by ik0adr** [comment]
On studying, not really. It is a problem of this component.

(homeassistant) homeassistant@hassbian:~/.homeassistant $ hass --script check_config
Testing configuration at /home/homeassistant/.homeassistant
WARNING:homeassistant.helpers.config_validation:Your configuration contains extra keys that the platform does not support.
Please remove [address].
Offending data: {"platform": "tts_bluetooth_speaker", "address": "41:42:D6:FA:B2:EA", "volume": "<redacted>"}

**Comment by fedemartini** [comment]
On HA 0.95 it’s marked as ‘invalid config’..
Do not know if works thow. Maybe a refurbishment is needed.. thanks a lot!!

**Comment by ik0adr** [comment]
Unfortunately from HA 0.95 this component does not work anymore.

**Comment by SeafireGit** [comment]
Is it planned to make it work again or is it dead ?

**Comment by ik0adr** [comment]
Author told me on email some time ago that he doesn't need this anymore.. So (very unfortunately)  it seems a dead branch, unless someone has the ability to make this compatible with the newer HA releases (not me.. would like to be able but not..)

**Comment by SeafireGit** [comment]
Thanks a lot for your reply! I wish I could help, but not able to neither. 

Le 24 août 2019 14:08:29 GMT+02:00, ik0adr <notifications@github.com> a écrit :
>Author told me on email some time ago that he doesn't need this
>anymore.. So it seems a dead branch, unless someone has the ability to
>make this compatible with the newer HA releases (not me.. would like to
>be able but not..) 
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/pkozul/ha-tts-bluetooth-speaker/issues/13#issuecomment-524545270

-- 
Envoyé de mon appareil Android avec Courriel K-9 Mail. Veuillez excuser ma brièveté.

**Comment by xumxum** [comment]
I fixed it, pull latest

**Comment by ik0adr** [comment]
Many many thanks!!!
