### ISSUE TITLE
Cannot Integrate BlueTooth_Speaker with HA

### ISSUE THREAD

**Issue by dreyerc6554** [pkozul/ha-tts-bluetooth-speaker#17]
Cannot find the reason why HA displays this error message when checking the configuration.
EVERYTHING is set as per instruction, with no formatting errors or missing files.

Configuration invalid
Platform error media_player.tts_bluetooth_speaker - Integration 'tts_bluetooth_speaker' not found.

**Comment by EduardJogi** [comment]
Same here :(

**Comment by xumxum** [comment]
Add the line bellow to the manifest.json file, new versions of Home Assistant MUST have it, wihtout it the plugin will be ignored, and not loaded.

  "version": "1.0.0"

**Comment by EduardJogi** [comment]
Hi xumxum,

Thanks for your reply.
I have added as you mentioned but still getting an error:
The top of the configurations looks like this:
<img width="479" alt="image" src="https://user-images.githubusercontent.com/77924843/142595277-b1dab956-dc2b-49d3-b515-5e179ddfb87a.png">

The custom_components folder is in the same folder as the configuration.yaml file.

Steps i followed:
- In configuration.yaml commented out the lines with Media Player.
- Restarted HA
- Remove the comment of the lines with Media player
  
I'm a newbie and just starting with Home Assistant.
Do you know what going wrong here?  Please let me know if you need more info.

**Comment by EduardJogi** [comment]
Hi xumxum, thank you for your tip and advice. This worked....

I'm a newbie, pls bare with me :)
I can see the speaker in HA but is says it's turned off.
Playing a song via the Linux cli (mplayer) works.

In the log of HA I'm getting the following Warning:
MediaPlayerDevice is deprecated, modify BluetoothSpeakerDevice to extend MediaPlayerEntity

Do you know how to solve this?

Thanks in advance.

**Comment by xumxum** [comment]
It seams the plugin interface changed in Home assistant and this plugin is not maintained anymore unfortunately. Try searching for an alternative perhaps, but in my experience Bluetooth speaker did not work so well for me on the long term, it was constantly disconnecting, or the speakers going to standby after some time..In the end I bought an usb sound card and had a permanent jack speaker connected for home assistant notifications..
If you really insist on having wireless , maybe look for a chromecast supporting speakers, though more pricey then the Bluetooth ones..

**Comment by EduardJogi** [comment]
Tnx for your quick reply. This configuration is on my test lab in an Oracle VM. I'm also using a PI4. I will try it on a the PI4 with the a jack.
Thanks a again.

**Comment by dreyerc6554** [comment]
VARIOUS attempts to get my BT speaker to work just with a HA on a PI4 did not work. 
I then constructed the following:
HA running on Debian10 / VirtualBox with Windows 10 as the OS. 
Setup VLC on Win10 Tablet + BT speaker.
Configure HA + Remote VLC to connect with VLC on Tablet & BT Speaker.
Then add to the setup,  in the garage a PI3 with VLC + Analog speakers
I am glad to tell you that everything is working. 
Lessons learn. Documentation & forums don't provide complete answers to all types of integrations or users' questions.
e.g Telling that a VM in bridge mode is the solution is very far from the truth when many novices don't understand NAT, Firewalls & on top of that virus SW that has ports restriction activated.
